version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn test

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install